version: '3.7'
services:
  db:
    container_name: mysqlAriad
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    ports:
    - 3306:3306
    expose:
    - '3306'
    volumes:
    - my-db:/var/lib/mysql
    networks:
    - ariad-net
  redis:
    container_name: redisAriad
    image: redis
    ports:
    - 6379:6379
    volumes:
    - my-redis:/data
    restart: always
    networks:
    - ariad-net
volumes:
  my-db: null
  my-redis: null
networks:
  ariad-net: null